[mgr]
prepend_keymap = [
	{ on = ["g","M"], run = "cd /mnt", desc = "Cd to /mnt" },
	{ on = ["g","d"], run = "cd /mnt/c/users/atmos/Downloads", desc = "Cd to windows download" },
	{ on = ["g","r"], run = "cd /", desc = "Cd to root" },
	{ on = "x", run = "cd /mnt", desc = "Cd to /mnt" },
  { on = ["d","d"], run = "yank --cut",desc = "cut files" },
  { on = ["d","D"], run = "remove --permanently",desc = "Permanently delete " },
  { on = ["d","T"], run = "remove", desc = "Trash selected files" },
  { on = "l", run = "plugin smart-enter", desc = "Enter directory / open file" },
  { on = ["z","h"],         run = "hidden toggle",               desc = "Toggle the visibility of hidden files" },
	{ on = ["z","f"],         run = "plugin fzf",                  desc = "Jump to a file/directory via fzf" },
	{ on = ["z","z"],         run = "plugin zoxide",               desc = "Jump to a directory via zoxide" },
	{ on = "K",          run = "arrow -50%", desc = "Move cursor up one page" },
	{ on = "J",          run = "arrow 50%",  desc = "Move cursor down one page" },

	{ on = "<PageUp>"    , run = "seek -10", desc = "Seek up 5 units in the preview" },
	{ on = "<PageDown>"  , run = "seek 10",  desc = "Seek down 5 units in the preview" },
	{ on = "<C-u>"       , run = "seek -10", desc = "Seek up 5 units in the preview" },
	{ on = "<C-d>"       , run = "seek 10",  desc = "Seek down 5 units in the preview" },
	{ on = "<C-k>"       , run = "seek -10", desc = "Seek up 5 units in the preview" },
	{ on = "<C-j>"       , run = "seek 10",  desc = "Seek down 5 units in the preview" },

	{ on = "i"           ,block=true, run = 'plugin toggle-pane max-preview',  desc = "Maximize or resotre the preview pane " },

  { on = ["t","c"], run = "tab_create --current", desc = "Create a new tab with CWD" },
	{ on = ["t","["], run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
	{ on = ["t","]"], run = "tab_switch 1 --relative",  desc = "Switch to next tab" },

	{ on = ["t","{"], run = "tab_swap -1", desc = "Swap current tab with previous tab" },
	{ on = ["t","}"], run = "tab_swap 1",  desc = "Swap current tab with next tab" },
]


