
require("wovim").setup({})
-- require("insis").setup({
--   clangd = {
--     enable = true,
--   },
--   git = {
--     current_line_blame = true,
--   },
--   lock_plugin_commit = false,
--   enable_imselect = true,
--   enable_very_magic_search = true,
--   lua = {
--     enable = true,
--   },
--   markdown = {
--     enable = true,
--     -- formatter = false,
--     format_on_save = true,
--   },
--   -- golang = {
--   --   enable = true,
--   --   format_on_save = true,
--   -- },
--   json = {
--     enable = true,
--     format_on_save = false,
--   },
--   yaml = {
--     enable = true,
--   -- },
--   -- docker = {
--   --   enable = true,
--   -- },
--   -- frontend = {
--   --   enable = true,
--   --   prisma = true,
--   --   vue = false,
--   --   format_on_save = true,
--   --   code_actions = "eslint_d",
--   --   ---@type "eslint_d" | "prettier"
--   --   formatter = "prettier",
--   --   cspell = false,
--   --   -- extra lsp command provided by typescript.nvim
--   --   typescript = {
--   --     keys = {
--   --       ts_organize = "gs",
--   --       ts_rename_file = "gR",
--   --       ts_add_missing_import = "ga",
--   --       ts_remove_unused = "gu",
--   --       ts_fix_all = "gf",
--   --       ts_goto_source = "gD",
--   --     },
--   --   },
--   -- },
--   -- yaml = {
--   --   enable = true,
--   --   format_on_save = true,
--   -- },
--   --
--   -- clangd = {
--   --   enable = true,
--   --   format_on_save = true,
--   -- },
--   --
--   -- rust = {
--   --   enable = true,
--   --   format_on_save = true,
--   -- },
--   --
--   bash = {
--     enable = true,
--     format_on_save = true,
--   },
--
--   python = {
--     enable = true,
--     format_on_save = true,
--   },
--   -- ruby = {
--   --   enable = true,
--   -- },
-- })
--
