If:
  PathMatch: .*\.cpp, .*\.cc

CompileFlags:
  Add: [-std=gnu++17,-I/home/atmosu/RSFROOT/include,-L/home/atmosu/RSFROOT/lib,-I/home/atmosu/temp/lapack-3.10.1/CBLAS/include]

---

If:
  PathMatch: .*\.c
  PathExclude: include/cumtb/

CompileFlags:
  Add: [-std=gnu17,-I/home/atmosu/RSFROOT/include,-L/home/atmosu/RSFROOT/lib,-I/home/atmosu/temp/lapack-3.10.1/CBLAS/include]
  Remove: [-W*]
---

If:
  PathMatch: .*vscan\.c
  
CompileFlags:
  Add: [ -I/home/atmosu/RSFSRC/build/user/chenyk,../../build/user/chenyk/fint1.o ../../build/user/chenyk/extend.o ]
  Remove: [-W*]
