If:
  PathMatch: .*\.cpp, .*\.cc

CompileFlags:
  Add: [-std=gnu++17,-I/home/akawcc/RSFROOT/include,-L/home/akawcc/RSFROOT/lib]

---

If:
  PathMatch: .*\.c
  PathExclude: include/cumtb/

CompileFlags:
  Add: [-std=gnu17,-I/home/akawcc/RSFROOT/include,-L/home/akawcc/RSFROOT/lib]
  Remove: [-W*]

